# Server
server.port=${SERVER_PORT}

# Application
spring.application.name=auth-service

# Database (PostgreSQL for production)
 spring.datasource.url=${DB_URL}
 spring.datasource.username=${DB_USERNAME}
 spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.refresh-token-expiration=${JWT_REFRESH_EXP}
jwt.access-token-expiration=${JWT_ACCESS_EXP}
jwt.issuer=${JWT_ISSUER}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging
logging.level.com.authservice=DEBUG
logging.level.org.springframework.security=INFO

# User Service URL
services.user.url=${USER_SERVICE_URL}

# TOTP Configuration
security.totp.issuer=AuthService
